# Use the Python3.7.2 image
FROM python:3.7.2-stretch

# Set the working directory to /app
WORKDIR /app

# Copy the requirements.txt over all by itself, then install the vendor packages.
# Doing these two things BEFORE you copy all your app code over allows you to
# avoid re-installing all the requirements every time you change your app code
# and rebuild.
COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Now that the dependancies are installed, we copy the current directory contents into the container at /app
ADD . /app

# run the command to start uWSGI
CMD ["uwsgi", "app.ini"]
